# -*- coding: utf-8 -*-
"""Data Analysis_Sales_csv.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xuxAVCoDrVmXLI0IEzKFWjBV1HMr7Ise

**Data Analysis on CSV Files**

Objective: Analyze sales data using Pandas.

Tools :Python, Pandas, Jupyter Notebook / Colab

Deliverables: Notebook + charts
"""

#importing libraries
import pandas as pd
import matplotlib.pyplot as plt

#load the dataset
from google.colab import files
uploaded= files.upload()

#Read the file
df= pd.read_csv('sales_data.csv')

#Check the first five rows of the data
df.head()

# Group by 'Product' and sum the 'Sales'
product_sales = df.groupby('Product_Category')['Sales_Amount'].sum()
product_sales

# Plot the total sales by product
plt.figure(figsize=(10, 6))
product_sales.plot(kind='bar', color='skyblue')
plt.title('Total Sales by Product')
plt.xlabel('Product')
plt.ylabel('Total Sales')

# Group by 'Date' and sum the 'Sales' to see daily trends
daily_sales = df.groupby('Sale_Date')['Sales_Amount'].sum()
daily_sales

# Plot the daily total sales
plt.figure(figsize=(12, 6))
daily_sales.plot(kind='line', marker='o', color='green')
plt.title('Daily Total Sales')
plt.xlabel('Date')
plt.ylabel('Total Sales')

# Plotting sales per product per day (can get busy with many products/days)
plt.figure(figsize=(12, 4))
df.pivot_table(index='Sale_Date', columns='Product_Category', values='Sales_Amount', aggfunc='sum').plot(kind='line', marker='o')

print("Basic data insights generated successfully.")